COMMIT;


CREATE TABLE SUCURSALES (
  SUCURSAL_ID INT NOT NULL PRIMARY KEY,
  NOMBRE VARCHAR(20) NOT NULL
);

CREATE TABLE ORDENES (
  ORDEN_ID INT NOT NULL PRIMARY KEY,
  SUCURSAL_ID INT NOT NULL,
  FECHA DATE NOT NULL,
  TOTAL DECIMAL NOT NULL,
  FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSALES(SUCURSAL_ID)
);

CREATE TABLE PRODUCTOS (
  PRODUCTO_ID INT NOT NULL PRIMARY KEY,
  ORDEN_ID INT NOT NULL,
  CODIGO VARCHAR2(20) NOT NULL,
  DESCRIPCION VARCHAR(200) NOT NULL,
  PRECIO DECIMAL NOT NULL,
  FOREIGN KEY (ORDEN_ID) REFERENCES ORDENES(ORDEN_ID)
);



INSERT INTO PRODUCTOS VALUES (1,18156,'ESMERILADORA ANGULAR','N/A',625);